export const DISPLAY_ADD_NEW_TRAIL = 'DISPLAY_ADD_NEW_TRAIL'
export type DISPLAY_ADD_NEW_TRAIL = typeof DISPLAY_ADD_NEW_TRAIL

export const DISPLAY_SEARCH_TRAIL = 'DISPLAY_SEARCH_TRAIL'
export type DISPLAY_SEARCH_TRAIL = typeof DISPLAY_SEARCH_TRAIL

export const DISPLAY_FILTER_TRAILS = 'DISPLAY_FILTER_TRAILS'
export type DISPLAY_FILTER_TRAILS = typeof DISPLAY_FILTER_TRAILS